import { randomBytes, scrypt, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";

const scryptAsync = promisify(scrypt) as (
  password: string,
  salt: Buffer,
  keylen: number,
) => Promise<Buffer>;

const KEYLEN = 64;
const PREFIX = "scrypt";

/**
 * The single-user login secret, stored as `scrypt$<salt>$<hash>`.
 *
 * Only the hash is ever written to `.env` — a leaked config file therefore does
 * not hand over the passphrase itself. scrypt rather than a plain digest because
 * this *is* a human-chosen password: it needs to be expensive to guess offline.
 * Generated by `cognitive-mirror auth set-passphrase`.
 */
export async function hashPassphrase(passphrase: string): Promise<string> {
  const salt = randomBytes(16);
  const hash = await scryptAsync(passphrase, salt, KEYLEN);
  return `${PREFIX}$${salt.toString("hex")}$${hash.toString("hex")}`;
}

/** Verify a passphrase against a stored hash. False on any malformed input. */
export async function verifyPassphrase(passphrase: string, stored: string): Promise<boolean> {
  const parts = stored.split("$");
  if (parts.length !== 3 || parts[0] !== PREFIX) return false;
  const salt = Buffer.from(parts[1]!, "hex");
  const expected = Buffer.from(parts[2]!, "hex");
  if (salt.length === 0 || expected.length !== KEYLEN) return false;
  const actual = await scryptAsync(passphrase, salt, KEYLEN);
  return timingSafeEqual(actual, expected);
}
